import Head from 'next/head';
import styled from 'styled-components';

const IndexBody = styled.div`
    width: 100%;
    height: 100vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;

    font-size: 30px;
    color: white;

`;

export default function Home() {
  return (
    <IndexBody>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello Playbingo Iframe
    </IndexBody>
  );
}
